//
//  TimerStyleKit.swift
//  Triggertrap
//
//  Created by Valentin Kalchev on 09/10/2015.
//  Copyright (c) 2015 Triggertrap Ltd. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class TimerStyleKit : NSObject {

    //// Drawing Methods

    public class func drawCircleTimer(fraction fraction: CGFloat = 0.337, clockwise: Bool = false, angle: CGFloat = 90, size: CGSize = CGSizeMake(200, 200), lineThickness: CGFloat = 4, nightTime: Bool = true) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()

        //// Color Declarations
        let fill = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
        let fill_Night = UIColor(red: 0.082, green: 0.082, blue: 0.082, alpha: 1.000)
        let foreground = UIColor(red: 0.514, green: 0.514, blue: 0.514, alpha: 1.000)
        let foreground_Night = UIColor(red: 0.243, green: 0.243, blue: 0.243, alpha: 1.000)

        //// Variable Declarations
        let expression: CGFloat = clockwise ? -fraction * 360 : fraction * 360
        let circleCenter: CGFloat = size.width - size.width / 2.0
        let circleSize: CGFloat = size.width - lineThickness
        let expression2: CGFloat = -circleSize / 2.0
        let foregroundColor = nightTime ? foreground_Night : foreground
        let fillColor = nightTime ? fill_Night : fill

        //// CircleBackground Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, circleCenter, circleCenter)

        let circleBackgroundPath = UIBezierPath(ovalInRect: CGRectMake(expression2, expression2, circleSize, circleSize))
        foregroundColor.setStroke()
        circleBackgroundPath.lineWidth = lineThickness
        circleBackgroundPath.stroke()

        CGContextRestoreGState(context)


        //// CircleBackground 2 Drawing
        CGContextSaveGState(context)
        CGContextTranslateCTM(context, circleCenter, circleCenter)
        CGContextRotateCTM(context, -angle * CGFloat(M_PI) / 180)

        let circleBackground2Rect = CGRectMake(expression2, expression2, circleSize, circleSize)
        let circleBackground2Path = UIBezierPath()
        circleBackground2Path.addArcWithCenter(CGPointMake(circleBackground2Rect.midX, circleBackground2Rect.midY), radius: circleBackground2Rect.width / 2, startAngle: 0 * CGFloat(M_PI)/180, endAngle: -expression * CGFloat(M_PI)/180, clockwise: true)

        fillColor.setStroke()
        circleBackground2Path.lineWidth = lineThickness
        circleBackground2Path.stroke()

        CGContextRestoreGState(context)
    }

}
